"""
ALPHA INVEST Telegram Bot
=========================
Provides a step-by-step conversational interface to TradingAgents.

Dialog flow:
  /start → Step 1: Ticker → Step 2: Language → Confirm → Analysis → PDF
"""

import asyncio
import io
import logging
import os
import sys
import time
from datetime import datetime
from pathlib import Path

# Add TradingAgents root to Python path
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from aiogram import Bot, Dispatcher, F
from aiogram.client.default import DefaultBotProperties
from aiogram.enums import ParseMode
from aiogram.filters import CommandStart, Command
from aiogram.fsm.context import FSMContext
from aiogram.fsm.storage.memory import MemoryStorage
from aiogram.types import (
    BufferedInputFile,
    CallbackQuery,
    Message,
)

from telegram_bot.config import (
    ANALYSTS,
    BOT_TOKEN,
    DEEP_THINK_LLM,
    GOOGLE_THINKING_LEVEL,
    LANGUAGES,
    LLM_PROVIDER,
    MAX_CONCURRENT,
    MAX_DEBATE_ROUNDS,
    MAX_RISK_DISCUSS_ROUNDS,
    QUICK_THINK_LLM,
    RATE_LIMIT_SECONDS,
)
from telegram_bot.keyboards import cancel_keyboard, confirm_keyboard, language_keyboard
from telegram_bot.pdf_generator import markdown_to_pdf, markdown_to_txt
from telegram_bot.states import AnalysisFlow

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger = logging.getLogger(__name__)

# ── Rate limiting & concurrency tracking ─────────────────────────────────────
_last_request: dict[int, float] = {}   # user_id → last analysis timestamp
_active_count = 0
_active_lock = asyncio.Lock()


# ── Helpers ───────────────────────────────────────────────────────────────────

def _build_config(language: str) -> dict:
    """Build TradingAgents config with hardcoded bot settings."""
    from tradingagents.default_config import DEFAULT_CONFIG
    cfg = dict(DEFAULT_CONFIG)
    cfg.update({
        "llm_provider":           LLM_PROVIDER,
        "quick_think_llm":        QUICK_THINK_LLM,
        "deep_think_llm":         DEEP_THINK_LLM,
        "google_thinking_level":  GOOGLE_THINKING_LEVEL,
        "max_debate_rounds":      MAX_DEBATE_ROUNDS,
        "max_risk_discuss_rounds": MAX_RISK_DISCUSS_ROUNDS,
        "output_language":        language,
    })
    return cfg


def _build_report_markdown(state: dict) -> str:
    """Assemble the final markdown report from agent state."""
    parts = ["# 📊 ALPHA INVEST — Investment Analysis Report\n"]

    ticker = state.get("company_of_interest", "")
    date   = state.get("trade_date", "")
    parts.append(f"**Ticker:** `{ticker}`  |  **Date:** {date}\n\n---\n")

    consensus_sig   = state.get("consensus_signal", "")
    consensus_score = state.get("consensus_score", 0)
    if consensus_sig:
        sign = "+" if consensus_score >= 0 else ""
        parts.append(
            f"## 🎯 Consensus Signal\n"
            f"**Signal:** {consensus_sig}  |  **Score:** {sign}{consensus_score}/6\n\n"
        )

    if state.get("multi_timeframe_report"):
        parts.append(f"## 📈 Multi-Timeframe Analysis\n{state['multi_timeframe_report']}\n")

    if state.get("consensus_report"):
        parts.append(f"## 🔀 Consensus Report\n{state['consensus_report']}\n")

    if state.get("market_report"):
        parts.append(f"## 📉 Market Analysis\n{state['market_report']}\n")

    if state.get("sentiment_report"):
        parts.append(f"## 💬 Sentiment Analysis\n{state['sentiment_report']}\n")

    if state.get("news_report"):
        parts.append(f"## 📰 News Analysis\n{state['news_report']}\n")

    if state.get("fundamentals_report"):
        parts.append(f"## 🏦 Fundamentals Analysis\n{state['fundamentals_report']}\n")

    debate = state.get("investment_debate_state", {})
    if debate.get("judge_decision"):
        parts.append(f"## ⚖️ Research Team Verdict\n{debate['judge_decision']}\n")

    if state.get("trader_investment_plan"):
        parts.append(f"## 🤝 Trader Plan\n{state['trader_investment_plan']}\n")

    risk = state.get("risk_debate_state", {})
    if risk.get("judge_decision"):
        parts.append(f"## 🛡️ Risk Management Verdict\n{risk['judge_decision']}\n")

    if state.get("final_trade_decision"):
        parts.append(
            f"---\n## 🏁 Final Decision\n\n{state['final_trade_decision']}\n\n"
            f"---\n*Generated by ALPHA INVEST Bot · {datetime.now().strftime('%Y-%m-%d %H:%M')}*\n"
        )

    return "\n".join(parts)


def _rate_limited(user_id: int) -> int | None:
    """Return remaining seconds if rate-limited, else None."""
    last = _last_request.get(user_id)
    if last is None:
        return None
    elapsed = time.time() - last
    if elapsed < RATE_LIMIT_SECONDS:
        return int(RATE_LIMIT_SECONDS - elapsed)
    return None


# ── Progress updater ─────────────────────────────────────────────────────────

AGENT_LABELS = {
    "Market Analyst":         "📉 Market Analyst",
    "Sentiment Analyst":      "💬 Sentiment Analyst",
    "News Analyst":           "📰 News Analyst",
    "Fundamentals Analyst":   "🏦 Fundamentals Analyst",
    "Multi Timeframe Analyst":"📊 Multi-Timeframe",
    "Consensus Agent":        "🎯 Consensus Agent",
    "Bull Researcher":        "🐂 Bull Researcher",
    "Bear Researcher":        "🐻 Bear Researcher",
    "Research Manager":       "⚖️  Research Manager",
    "Trader":                 "💼 Trader",
    "Aggressive Analyst":     "🔥 Aggressive Risk",
    "Conservative Analyst":   "🧊 Conservative Risk",
    "Neutral Analyst":        "🌿 Neutral Risk",
    "Portfolio Manager":      "🏦 Portfolio Manager",
}

ALL_AGENTS = list(AGENT_LABELS.keys())


def _progress_text(ticker: str, completed: list[str], current: str, elapsed: int) -> str:
    mins, secs = divmod(elapsed, 60)
    lines = [
        f"⏳ **Анализ {ticker}** — {mins:02d}:{secs:02d}\n",
        "```",
    ]
    for agent in ALL_AGENTS:
        label = AGENT_LABELS[agent]
        if agent in completed:
            lines.append(f"✅ {label}")
        elif agent == current:
            lines.append(f"🔄 {label}")
        else:
            lines.append(f"⬜ {label}")
    lines.append("```")
    return "\n".join(lines)


# ── Core analysis runner ─────────────────────────────────────────────────────

async def _run_analysis(
    bot: Bot,
    chat_id: int,
    progress_msg_id: int,
    ticker: str,
    language: str,
    state_obj: FSMContext,
):
    """Run TradingAgents in a thread and stream progress to Telegram."""
    global _active_count

    from tradingagents.graph.trading_graph import TradingAgentsGraph

    config = _build_config(language)
    trade_date = datetime.now().strftime("%Y-%m-%d")
    start_time = time.time()
    completed: list[str] = []
    current_agent = ALL_AGENTS[0]

    async def _update_progress(current: str):
        elapsed = int(time.time() - start_time)
        text = _progress_text(ticker, completed, current, elapsed)
        try:
            await bot.edit_message_text(
                chat_id=chat_id,
                message_id=progress_msg_id,
                text=text,
                parse_mode=ParseMode.MARKDOWN,
                reply_markup=cancel_keyboard(),
            )
        except Exception:
            pass  # ignore edit throttle errors

    # Periodic progress updater task
    async def _periodic_updater():
        while True:
            await asyncio.sleep(15)
            await _update_progress(current_agent)

    updater_task = asyncio.create_task(_periodic_updater())

    try:
        # Run TradingAgents in a thread pool (it's synchronous)
        loop = asyncio.get_event_loop()

        def _sync_run():
            graph = TradingAgentsGraph(
                selected_analysts=ANALYSTS,
                debug=False,
                config=config,
            )
            final_state, signal = graph.propagate(ticker, trade_date)
            return final_state, signal

        final_state, signal = await loop.run_in_executor(None, _sync_run)

        updater_task.cancel()

        # Mark all complete
        completed = ALL_AGENTS[:]
        elapsed = int(time.time() - start_time)
        mins, secs = divmod(elapsed, 60)
        await bot.edit_message_text(
            chat_id=chat_id,
            message_id=progress_msg_id,
            text=f"✅ **Анализ завершён** — {mins:02d}:{secs:02d}\n\nГенерирую PDF отчет...",
            parse_mode=ParseMode.MARKDOWN,
        )

        # Build and send report
        report_md = _build_report_markdown(final_state)
        date_str = datetime.now().strftime("%Y-%m-%d")
        pdf_bytes = markdown_to_pdf(report_md, ticker, date_str)

        if pdf_bytes:
            filename = f"ALPHA_INVEST_{ticker}_{date_str}.pdf"
            await bot.send_document(
                chat_id=chat_id,
                document=BufferedInputFile(pdf_bytes, filename=filename),
                caption=(
                    f"📊 **{ticker}** — Investment Analysis\n"
                    f"🎯 Signal: **{signal}**\n"
                    f"📅 {date_str}\n\n"
                    f"_Powered by ALPHA INVEST · TradingAgents_"
                ),
                parse_mode=ParseMode.MARKDOWN,
            )
        else:
            # Fallback: send as .md text file
            txt_bytes = markdown_to_txt(report_md)
            filename = f"ALPHA_INVEST_{ticker}_{date_str}.txt"
            await bot.send_document(
                chat_id=chat_id,
                document=BufferedInputFile(txt_bytes, filename=filename),
                caption=f"📊 **{ticker}** — Signal: **{signal}**",
                parse_mode=ParseMode.MARKDOWN,
            )

        # Brief final signal message
        await bot.send_message(
            chat_id=chat_id,
            text=(
                f"🏁 **Итоговый сигнал: {signal}**\n\n"
                f"Полный отчёт прикреплён выше ☝️\n"
                f"Для нового анализа нажми /start"
            ),
            parse_mode=ParseMode.MARKDOWN,
        )

    except asyncio.CancelledError:
        updater_task.cancel()
        await bot.send_message(
            chat_id=chat_id,
            text="🛑 Анализ отменён. Нажми /start для нового запроса.",
        )
    except Exception as e:
        updater_task.cancel()
        logger.exception("Analysis failed for %s: %s", ticker, e)
        await bot.send_message(
            chat_id=chat_id,
            text=(
                f"❌ Ошибка при анализе **{ticker}**:\n`{e}`\n\n"
                f"Попробуй снова через /start"
            ),
            parse_mode=ParseMode.MARKDOWN,
        )
    finally:
        async with _active_lock:
            _active_count -= 1
        _last_request[chat_id] = time.time()
        await state_obj.clear()


# ── Handler registration ─────────────────────────────────────────────────────

def register_handlers(dp: Dispatcher):

    # /start
    @dp.message(CommandStart())
    async def cmd_start(message: Message, state: FSMContext):
        await state.clear()
        await message.answer(
            "👋 Добро пожаловать в **ALPHA INVEST Bot**!\n\n"
            "Я проведу полный hedge-fund анализ любой публичной компании:\n"
            "📉 Технический · 📰 Новостной · 💬 Сентимент · 🏦 Фундаментальный\n\n"
            "━━━━━━━━━━━━━━━━━━━━\n"
            "📌 **Шаг 1 из 2** — Введи тикер акции:\n"
            "_(Примеры: `AAPL`, `SBER.ME`, `7203.T`, `0700.HK`)_",
            parse_mode=ParseMode.MARKDOWN,
        )
        await state.set_state(AnalysisFlow.waiting_ticker)

    # Ticker input
    @dp.message(AnalysisFlow.waiting_ticker)
    async def handle_ticker(message: Message, state: FSMContext):
        raw = message.text.strip().upper()

        # Validate ticker format
        if not raw or not all(c.isalnum() or c in "._-^" for c in raw) or len(raw) > 32:
            await message.answer(
                "⚠️ Некорректный тикер. Используй только буквы, цифры и символы `.`, `-`, `^`.\n"
                "Пример: `AAPL`, `SBER.ME`, `005930.KS`",
                parse_mode=ParseMode.MARKDOWN,
            )
            return

        await state.update_data(ticker=raw)
        await message.answer(
            f"✅ Тикер: **{raw}**\n\n"
            "━━━━━━━━━━━━━━━━━━━━\n"
            "🌐 **Шаг 2 из 2** — Выбери язык отчёта:",
            parse_mode=ParseMode.MARKDOWN,
            reply_markup=language_keyboard(),
        )
        await state.set_state(AnalysisFlow.waiting_language)

    # Language selection
    @dp.callback_query(AnalysisFlow.waiting_language, F.data.startswith("lang:"))
    async def handle_language(callback: CallbackQuery, state: FSMContext):
        language = callback.data.split(":", 1)[1]
        data = await state.get_data()
        ticker = data["ticker"]
        await state.update_data(language=language)

        lang_label = next(
            (k for k, v in LANGUAGES.items() if v == language), language
        )

        await callback.message.edit_text(
            f"━━━━━━━━━━━━━━━━━━━━\n"
            f"📋 **Параметры анализа:**\n\n"
            f"📌 Тикер: **{ticker}**\n"
            f"🌐 Язык отчёта: **{lang_label}**\n"
            f"📅 Дата: **{datetime.now().strftime('%Y-%m-%d')}**\n"
            f"👥 Аналитики: Market · News · Sentiment · Fundamentals\n"
            f"⚡ Модель: Gemini 2.0 Flash (Thinking)\n\n"
            f"━━━━━━━━━━━━━━━━━━━━\n"
            f"⏱ Ожидаемое время анализа: **5–15 минут**\n\n"
            f"Запустить?",
            parse_mode=ParseMode.MARKDOWN,
            reply_markup=confirm_keyboard(ticker, language),
        )
        await state.set_state(AnalysisFlow.confirming)
        await callback.answer()

    # Confirm → launch analysis
    @dp.callback_query(AnalysisFlow.confirming, F.data == "confirm:yes")
    async def handle_confirm(callback: CallbackQuery, state: FSMContext):
        global _active_count
        user_id = callback.from_user.id
        data = await state.get_data()
        ticker   = data["ticker"]
        language = data["language"]

        # Rate limit check
        remaining = _rate_limited(user_id)
        if remaining is not None:
            hours, rem = divmod(remaining, 3600)
            mins, secs = divmod(rem, 60)
            await callback.answer(
                f"⏳ Лимит: 1 анализ в 3 часа.\nПодожди {hours:02d}:{mins:02d}:{secs:02d} до следующего запроса.",
                show_alert=True,
            )
            return

        # Concurrency check
        async with _active_lock:
            if _active_count >= MAX_CONCURRENT:
                await callback.answer(
                    "🔄 Сервер загружен (заняты все слоты).\nПодожди пару минут и попробуй снова.",
                    show_alert=True,
                )
                return
            _active_count += 1

        await callback.message.edit_reply_markup(reply_markup=None)

        # Send initial progress message
        progress_msg = await callback.message.answer(
            _progress_text(ticker, [], ALL_AGENTS[0], 0),
            parse_mode=ParseMode.MARKDOWN,
            reply_markup=cancel_keyboard(),
        )
        await state.set_state(AnalysisFlow.running)
        await state.update_data(progress_msg_id=progress_msg.message_id)
        await callback.answer()

        # Launch analysis as background task
        asyncio.create_task(
            _run_analysis(
                bot=callback.bot,
                chat_id=callback.message.chat.id,
                progress_msg_id=progress_msg.message_id,
                ticker=ticker,
                language=language,
                state_obj=state,
            )
        )

    # Cancel before confirm
    @dp.callback_query(AnalysisFlow.confirming, F.data == "confirm:no")
    async def handle_cancel_confirm(callback: CallbackQuery, state: FSMContext):
        await state.clear()
        await callback.message.edit_text(
            "❌ Анализ отменён. Нажми /start для нового запроса.",
            reply_markup=None,
        )
        await callback.answer()

    # Cancel during analysis
    @dp.callback_query(AnalysisFlow.running, F.data == "cancel_analysis")
    async def handle_cancel_running(callback: CallbackQuery, state: FSMContext):
        await state.clear()
        await callback.message.edit_text(
            "🛑 Анализ отменён. Нажми /start для нового запроса.",
            reply_markup=None,
        )
        await callback.answer("Отменено")

    # /help
    @dp.message(Command("help"))
    async def cmd_help(message: Message):
        await message.answer(
            "📖 **ALPHA INVEST Bot — Помощь**\n\n"
            "🔹 /start — начать новый анализ\n"
            "🔹 /help  — показать эту справку\n\n"
            "**Что делает бот:**\n"
            "Запускает полный hedge-fund анализ акции:\n"
            "• 📉 Технический (рынок + Multi-Timeframe)\n"
            "• 📰 Новостной + инсайдерские сделки\n"
            "• 💬 Сентимент-анализ\n"
            "• 🏦 Фундаментальный (DCF, WACC, Comps)\n"
            "• 🐂🐻 Bull vs Bear debate\n"
            "• 🛡️ Risk Management\n"
            "• 🏁 Итоговый сигнал + PDF отчёт\n\n"
            "**Ограничения:**\n"
            "• 1 анализ в 3 часа на пользователя\n"
            "• Время анализа: 5–15 минут\n"
            "• Формат тикера: `AAPL`, `SBER.ME`, `7203.T`",
            parse_mode=ParseMode.MARKDOWN,
        )


# ── Main ─────────────────────────────────────────────────────────────────────

async def main():
    if not BOT_TOKEN:
        raise RuntimeError(
            "TELEGRAM_BOT_TOKEN не задан. Добавь его в .env или переменные окружения."
        )

    bot = Bot(
        token=BOT_TOKEN,
        default=DefaultBotProperties(parse_mode=ParseMode.MARKDOWN),
    )
    dp = Dispatcher(storage=MemoryStorage())
    register_handlers(dp)

    logger.info("ALPHA INVEST Bot запущен (polling)...")
    await dp.start_polling(bot, skip_updates=True)


if __name__ == "__main__":
    asyncio.run(main())
