"""
PDF generator: converts a Markdown analysis report to a styled PDF.
Uses markdown2 + weasyprint (HTML → PDF pipeline).
Falls back to plain .txt if weasyprint is unavailable.
"""

import io
import logging
from pathlib import Path

logger = logging.getLogger(__name__)

# CSS styles for the PDF
_CSS = """
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap');

* { box-sizing: border-box; margin: 0; padding: 0; }

body {
    font-family: 'Inter', 'Helvetica Neue', Arial, sans-serif;
    font-size: 11pt;
    line-height: 1.6;
    color: #1a1a2e;
    background: #ffffff;
    padding: 30px 40px;
}

h1 { font-size: 20pt; color: #0f3460; border-bottom: 3px solid #e94560; padding-bottom: 8px; margin: 24px 0 12px; }
h2 { font-size: 15pt; color: #16213e; border-left: 4px solid #e94560; padding-left: 10px; margin: 20px 0 10px; }
h3 { font-size: 12pt; color: #0f3460; margin: 16px 0 8px; }

p  { margin: 8px 0; }
ul, ol { margin: 8px 0 8px 24px; }
li { margin: 4px 0; }

table {
    width: 100%;
    border-collapse: collapse;
    margin: 12px 0;
    font-size: 10pt;
}
th {
    background: #0f3460;
    color: #ffffff;
    padding: 8px 10px;
    text-align: left;
    font-weight: 600;
}
td {
    padding: 7px 10px;
    border-bottom: 1px solid #e0e0e0;
}
tr:nth-child(even) td { background: #f5f7fa; }

code {
    background: #f0f4f8;
    border-radius: 3px;
    padding: 2px 5px;
    font-family: 'Courier New', monospace;
    font-size: 10pt;
}
pre {
    background: #1a1a2e;
    color: #e0e0e0;
    padding: 14px;
    border-radius: 6px;
    margin: 10px 0;
    overflow-x: auto;
    font-size: 9.5pt;
}
pre code { background: none; padding: 0; color: inherit; }

blockquote {
    border-left: 4px solid #e94560;
    padding: 8px 14px;
    margin: 10px 0;
    background: #fdf6f6;
    color: #555;
}

.footer {
    margin-top: 40px;
    padding-top: 14px;
    border-top: 2px solid #e94560;
    text-align: center;
    font-size: 9pt;
    color: #888;
}
"""

_HEADER_TEMPLATE = """<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8"/>
  <style>{css}</style>
</head>
<body>
  <div style="text-align:center; margin-bottom:28px;">
    <h1 style="border:none; font-size:24pt; color:#e94560; letter-spacing:2px;">ALPHA INVEST</h1>
    <p style="color:#888; font-size:10pt;">AI-Powered Hedge Fund Analysis</p>
  </div>
  {body}
  <div class="footer">
    Generated by ALPHA INVEST Bot &bull; TradingAgents Framework &bull; {date}
  </div>
</body>
</html>"""


def markdown_to_pdf(markdown_text: str, ticker: str, date: str) -> bytes | None:
    """
    Convert markdown report to PDF bytes.
    Currently disabled (always returns None) due to Weasyprint causing OOM 
    crashes on Render.com free tier. The bot will fallback to .txt automatically.
    """
    logger.warning("PDF generation disabled to prevent OOM crash — returning None")
    return None


def sanitize_repetition_loops(text: str) -> str:
    """Detect and clean up infinite token generation loops (like repeating spaces, dashes, dots, or tables)."""
    import re
    # 1. Fix repeating lines of dashes/colons/pipes (often generated in markdown table loops)
    # If a line like "----" or ":----" or "|----" is repeated more than 3 times sequentially, keep only 1
    lines = text.split("\n")
    cleaned_lines = []
    prev_line = None
    repeat_count = 0
    for line in lines:
        stripped = line.strip()
        # Is it a markdown table border or dash separator line?
        is_dash_or_separator = len(stripped) > 3 and all(c in "-:| " for c in stripped)
        # Is it mostly empty spaces?
        is_empty_or_spaces = not stripped
        
        if is_dash_or_separator or is_empty_or_spaces:
            if stripped == prev_line:
                repeat_count += 1
                if repeat_count > 2:
                    continue # Skip repeating lines
            else:
                prev_line = stripped
                repeat_count = 1
        else:
            prev_line = None
            repeat_count = 0
            
        cleaned_lines.append(line)
        
    text = "\n".join(cleaned_lines)
    
    # 2. Fix inline repeating patterns (e.g. "--------------------------------------...")
    # Replace more than 30 consecutive dashes with a standard markdown separator
    text = re.sub(r'-{30,}', '---', text)
    
    # 3. Replace long runs of spaces (e.g. more than 30 spaces)
    text = re.sub(r' {30,}', ' ', text)
    
    # 4. Remove multiple empty lines (limit to max 3 consecutive newlines)
    text = re.sub(r'\n{4,}', '\n\n\n', text)
    
    return text


def markdown_to_txt(markdown_text: str) -> bytes:
    """Fallback: return markdown as UTF-8 encoded bytes (plain text file)."""
    cleaned_text = sanitize_repetition_loops(markdown_text)
    return cleaned_text.encode("utf-8")
